3. Ensembl
4. Expression Atlas
5. Uniprot
GO Annotations
6. IntAct
From UniProt page -> Protein-protein interactions
Check detection method
7. Alphafold

```{r}
pacman::p_load(tidyverse, readxl, gtsummary, gt, googlesheets4)

belen_db = readxl::read_xlsx("EDUARDO bd_proyecto_v.02.xlsx", sheet="consolidado")
colnames(belen_db)


tab1 = belen_db |>
select("año", "DepartamentoPaciente","Sexo", "Edad", dxfinal="Diagnóstico final")  |>
filter(dxfinal!="POSITIVO II") |>
mutate(dxfinal=ifelse(dxfinal=="NEGATIVO", dxfinal, "POSITIVO"),
Sexo=ifelse(Sexo%in%c("F", "M"), Sexo, NA),
Edad=as.numeric(Edad),
DepartamentoPaciente = as.factor(case_when(
            DepartamentoPaciente  %in% c("AMAZONAS", "LORETO", "MADRE_DE_DIOS", "SAN_MARTIN", "SAN MARTIN", "UCAYALI") ~ "Amazonian region",
            DepartamentoPaciente  %in% c("ANCASH", "AREQUIPA", "AREQUIPÁ", "CALLAO", "ICA", "LA_LIBERTAD", "LA LIBERTAD",  "LAMBAYEQUE", "LIMA", "MOQUEGUA", "PIURA", "TACNA", "TUMBES") ~ "Coastal region",
            DepartamentoPaciente %in% c("PUNO", "HUANCAVELICA", "HUANUCO", "APURIMAC", "AYACUCHO", "CAJAMARCA", "JUNIN", "PASCO",  "CUSCO") ~ "Andean region",
            DepartamentoPaciente%in%c("CAÑETE", "CHICLAYO", "CHIMBOTE", "CHINCHA", "CHOSICA", "DIRESA LIMA", "HEVES", "HUYCAN", "INSTITUTO NACIONAL DE ENFERMEDADES NEOPLASICAS", "JESUS MARIA", "LABAYEQUE", "LIMA CENTRO", "LIMA ESTE", "LIMA SUR", "liMA-", "LIMA-", "ROM: JESUS MARIA", "SULLANA", "SAN VICENTE", "TRUJILLLO", "TRUJILLO") ~ "Coastal region",
            DepartamentoPaciente%in%c(
                "HOSPITAL SAN JUAN DE KIMBIRI-VRAEM", "MADRE DE DIOS", "OXAPAMPA", "PUERO MALDONADO", "PUERTO MALDONADO", "TARAPOTO"
            ) ~ "Amazonian region",
            DepartamentoPaciente%in%c(
                "HUANCAYO", "HUARAL") ~ "Andean region",
            .default=NA)))  |>
gtsummary::tbl_summary(
    by="dxfinal",
    missing="no"
) |>
 modify_header(
        label = "**Variable**", 
        all_stat_cols() ~ "**{level}**, N={n} ({style_percent(p, digits=1)}%)"
    ) |>
    add_overall(last=FALSE, col_label="**Total**") %>%
    bold_labels() %>%
    add_p( test.args = all_tests("fisher.test") ~ list(simulate.p.value = TRUE)) |>
    as_gt()

gtsave(tab1, "2604_belen_tab1.docx")

as.numeric(belen_db$Edad)
```

```{r}

belen_db |>
    select(Paciente, ID="dni/cédula", dxfinal="Diagnóstico final") |>
    filter(dxfinal!="POSITIVO II") |>
    mutate(dxfinal=ifelse(dxfinal=="NEGATIVO", dxfinal, "POSITIVO"))

bd_inen = read_sheet("https://docs.google.com/spreadsheets/d/1vSKNI5KHHmMwOmdy-xlW4vacsPPXJUKb3aY30zQAkJs/edit?gid=404973295#gid=404973295") |>
mutate(Paciente=paste0(ApPaterno, " ", ApMaterno, ", ", Nombres))

leftj=belen_db |>
    left_join(bd_inen, by=c("dni/cédula"="NumDocu"))

view(leftj)


```
